### ISSUE TITLE
after migration all repositories became public

### ISSUE THREAD

**Issue by tomtom125** [kumlali/gogs2gitea#1]
Hi,

I've just migrated all org and repos from one gitea to another gitea. Everything seems to be good.
All the src repos were private but the migratated repos became public.
How can I migrate to keep this private settngs of all repositories?

Thanks,
Tom

**Comment by kumlali** [comment]
Hi Tom,

I am not sure if it is possible to find out whether a repository is private or public. I could not find any response attribute stating that in https://try.gitea.io/api/swagger#/repository/repoGet. Another API function would provide that, though.

After you know that your source repository is private, you would change https://github.com/kumlali/gogs2gitea/blob/master/migrate.py#L227 as follows: 

`post(get_api_url(url) + '/org/' + org + '/repos', {'name': repo, 'private': true}, token)`

I am not sure if it works because I did not try it. Please have a look at https://try.gitea.io/api/swagger for all the API functions and possibilities.

Regards,

Ali Sadık

**Comment by tomtom125** [comment]
Hi Ali, Thanks. Menwile I&#39;ve solved it in an other way. Regards,Tom
"Ali Sadık Kumlalı" <notifications@github.com> írta:
